apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  FEATURE_FLAGS: "feature1,feature2,feature3"
  LOG_LEVEL: "info"
  CACHE_TTL: "3600"
---
apiVersion: v1
kind: Secret
metadata:
  name: external-secrets
type: Opaque
data:
  AWS_SECRET: ZnJvbS1hd3Mtc2VjcmV0cy1tYW5hZ2Vy
  GCP_SECRET: ZnJvbS1nY3Atc2VjcmV0LW1hbmFnZXI=
  AZURE_SECRET: ZnJvbS1henVyZS1rZXl2YXVsdA==
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: registry.example.com/api:v1.5
          ports:
            - containerPort: 8080
          env:
            - name: CLOUD_PROVIDER
              value: "multi"
            - name: TELEMETRY_ENDPOINT
              value: "otel-collector:4317"
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: external-secrets
          volumeMounts:
            - name: shared-data-volume
              mountPath: /data/shared-data
      volumes:
        - name: shared-data-volume
          persistentVolumeClaim:
            claimName: shared-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  labels:
    app: admin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: registry.example.com/admin:v2.0
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
          envFrom:
            - secretRef:
                name: external-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: api
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: admin
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: global-ingress-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - global.example.com
      secretName: wildcard-tls
  rules:
    - host: global.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api-service
                port:
                  number: 80
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-service
                port:
                  number: 80
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-cronjob
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: backup-cronjob
              image: backup-utility:latest
              command: ["/bin/sh"]
              args: ["-c","backup-script.sh"]
          restartPolicy: OnFailure