import { Node, Edge } from 'reactflow';
import { K8sNodeData } from '@/types/k8s';

export interface DiagramTemplate {
  id: string;
  name: string;
  description: string;
  nodes: Node<K8sNodeData>[];
  edges: Edge[];
}

export const templates: DiagramTemplate[] = [
  {
    id: 'simple-app',
    name: 'Simple App',
    description: 'Ingress → Service → Deployment',
    nodes: [
      {
        id: 'ingress-1',
        type: 'k8sNode',
        position: { x: 100, y: 100 },
        data: {
          type: 'ingress',
          label: 'Web Ingress',
          host: 'myapp.example.com',
          paths: [{ path: '/', pathType: 'Prefix', serviceName: '', servicePort: 80 }],
          ingressClassName: 'nginx',
          enableTLS: false,
          tlsSecretName: '',
          annotations: [],
        },
      },
      {
        id: 'service-1',
        type: 'k8sNode',
        position: { x: 100, y: 250 },
        data: {
          type: 'service',
          label: 'Web Service',
          serviceName: 'web-service',
          port: 80,
          targetPort: 8080,
          serviceType: 'ClusterIP',
          selectorLabels: [{ key: 'app', value: 'web' }],
        },
      },
      {
        id: 'deployment-1',
        type: 'k8sNode',
        position: { x: 100, y: 400 },
        data: {
          type: 'deployment',
          label: 'Web Deployment',
          deploymentName: 'web-deployment',
          replicas: 1,
          containerName: 'web',
          image: 'nginx:alpine',
          containerPort: 80,
          envVars: [],
          labels: [{ key: 'app', value: 'web' }],
          volumeMounts: [],
        },
      },
    ],
    edges: [
      { id: 'e1-2', source: 'ingress-1', target: 'service-1' },
      { id: 'e2-3', source: 'service-1', target: 'deployment-1' },
    ],
  },
  {
    id: 'multi-path',
    name: 'Multi-Path App',
    description: 'Ingress → Multiple Services',
    nodes: [
      {
        id: 'ingress-1',
        type: 'k8sNode',
        position: { x: 200, y: 50 },
        data: {
          type: 'ingress',
          label: 'API Gateway',
          host: 'api.example.com',
          paths: [
            { path: '/api', pathType: 'Prefix', serviceName: 'api-service', servicePort: 80 },
            { path: '/web', pathType: 'Prefix', serviceName: 'web-service', servicePort: 80 },
          ],
          ingressClassName: 'nginx',
          enableTLS: false,
          tlsSecretName: '',
          annotations: [],
        },
      },
      {
        id: 'service-api',
        type: 'k8sNode',
        position: { x: 50, y: 200 },
        data: {
          type: 'service',
          label: 'API Service',
          serviceName: 'api-service',
          port: 80,
          targetPort: 3000,
          serviceType: 'ClusterIP',
          selectorLabels: [{ key: 'app', value: 'api' }],
        },
      },
      {
        id: 'service-web',
        type: 'k8sNode',
        position: { x: 350, y: 200 },
        data: {
          type: 'service',
          label: 'Web Service',
          serviceName: 'web-service',
          port: 80,
          targetPort: 80,
          serviceType: 'ClusterIP',
          selectorLabels: [{ key: 'app', value: 'web' }],
        },
      },
      {
        id: 'deployment-api',
        type: 'k8sNode',
        position: { x: 50, y: 350 },
        data: {
          type: 'deployment',
          label: 'API Deployment',
          deploymentName: 'api-deployment',
          replicas: 2,
          containerName: 'api',
          image: 'node:18-alpine',
          containerPort: 3000,
          envVars: [],
          labels: [{ key: 'app', value: 'api' }],
          volumeMounts: [],
        },
      },
      {
        id: 'deployment-web',
        type: 'k8sNode',
        position: { x: 350, y: 350 },
        data: {
          type: 'deployment',
          label: 'Web Deployment',
          deploymentName: 'web-deployment',
          replicas: 2,
          containerName: 'web',
          image: 'nginx:alpine',
          containerPort: 80,
          envVars: [],
          labels: [{ key: 'app', value: 'web' }],
          volumeMounts: [],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'ingress-1', target: 'service-api' },
      { id: 'e2', source: 'ingress-1', target: 'service-web' },
      { id: 'e3', source: 'service-api', target: 'deployment-api' },
      { id: 'e4', source: 'service-web', target: 'deployment-web' },
    ],
  },
  {
    id: 'microservices',
    name: 'Microservices',
    description: 'Full stack with ConfigMap & Secret',
    nodes: [
      {
        id: 'ingress-1',
        type: 'k8sNode',
        position: { x: 300, y: 50 },
        data: {
          type: 'ingress',
          label: 'Main Ingress',
          host: 'app.example.com',
          paths: [{ path: '/', pathType: 'Prefix', serviceName: 'backend-service', servicePort: 80 }],
          ingressClassName: 'nginx',
          enableTLS: true,
          tlsSecretName: 'tls-secret',
          annotations: [],
        },
      },
      {
        id: 'service-1',
        type: 'k8sNode',
        position: { x: 300, y: 180 },
        data: {
          type: 'service',
          label: 'Backend Service',
          serviceName: 'backend-service',
          port: 80,
          targetPort: 8080,
          serviceType: 'ClusterIP',
          selectorLabels: [{ key: 'app', value: 'backend' }],
        },
      },
      {
        id: 'deployment-1',
        type: 'k8sNode',
        position: { x: 300, y: 320 },
        data: {
          type: 'deployment',
          label: 'Backend',
          deploymentName: 'backend',
          replicas: 3,
          containerName: 'backend',
          image: 'myapp/backend:latest',
          containerPort: 8080,
          envVars: [],
          labels: [{ key: 'app', value: 'backend' }],
          volumeMounts: [],
        },
      },
      {
        id: 'configmap-1',
        type: 'k8sNode',
        position: { x: 50, y: 450 },
        data: {
          type: 'configmap',
          label: 'App Config',
          name: 'app-config',
          data: [
            { key: 'DATABASE_HOST', value: 'postgres.default.svc' },
            { key: 'REDIS_HOST', value: 'redis.default.svc' },
          ],
        },
      },
      {
        id: 'secret-1',
        type: 'k8sNode',
        position: { x: 300, y: 500 },
        data: {
          type: 'secret',
          label: 'DB Credentials',
          name: 'db-credentials',
          secretType: 'Opaque',
          data: [
            { key: 'DB_USER', value: 'admin' },
            { key: 'DB_PASSWORD', value: 'supersecret' },
          ],
        },
      },
      {
        id: 'pvc-1',
        type: 'k8sNode',
        position: { x: 550, y: 450 },
        data: {
          type: 'pvc',
          label: 'Data Volume',
          name: 'data-pvc',
          storageClassName: 'standard',
          size: '10Gi',
          accessModes: ['ReadWriteOnce'],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'ingress-1', target: 'service-1' },
      { id: 'e2', source: 'service-1', target: 'deployment-1' },
      { id: 'e3', source: 'deployment-1', target: 'configmap-1' },
      { id: 'e4', source: 'deployment-1', target: 'secret-1' },
      { id: 'e5', source: 'deployment-1', target: 'pvc-1' },
    ],
  },
  {
    id: 'cronjob-system',
    name: 'CronJob System',
    description: 'Scheduled jobs with configuration',
    nodes: [
      {
        id: 'cronjob-1',
        type: 'k8sNode',
        position: { x: 200, y: 100 },
        data: {
          type: 'cronjob',
          label: 'Backup Job',
          name: 'backup-cronjob',
          schedule: '0 2 * * *',
          image: 'backup-tool:latest',
          command: ['/bin/sh', '-c'],
          args: ['backup.sh'],
        },
      },
      {
        id: 'configmap-1',
        type: 'k8sNode',
        position: { x: 50, y: 280 },
        data: {
          type: 'configmap',
          label: 'Backup Config',
          name: 'backup-config',
          data: [
            { key: 'BACKUP_PATH', value: '/data/backup' },
            { key: 'RETENTION_DAYS', value: '30' },
          ],
        },
      },
      {
        id: 'secret-1',
        type: 'k8sNode',
        position: { x: 350, y: 280 },
        data: {
          type: 'secret',
          label: 'S3 Credentials',
          name: 's3-credentials',
          secretType: 'Opaque',
          data: [
            { key: 'AWS_ACCESS_KEY', value: 'AKIAIOSFODNN7' },
            { key: 'AWS_SECRET_KEY', value: 'secret123' },
          ],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'cronjob-1', target: 'configmap-1' },
      { id: 'e2', source: 'cronjob-1', target: 'secret-1' },
    ],
  },
  {
    id: 'aws-eks-app',
    name: 'AWS EKS Application',
    description: 'AWS EKS with ALB Ingress, ECR, EBS, and auto-scaling',
    nodes: [
      {
        id: 'ingress-1',
        type: 'k8sNode',
        position: { x: 250, y: 50 },
        data: {
          type: 'ingress',
          label: 'ALB Ingress',
          host: 'app.example.com',
          paths: [{ path: '/', pathType: 'Prefix', serviceName: 'app-service', servicePort: 80 }],
          ingressClassName: 'alb',
          enableTLS: true,
          tlsSecretName: 'tls-cert',
          annotations: [
            { key: 'alb.ingress.kubernetes.io/scheme', value: 'internet-facing' },
            { key: 'alb.ingress.kubernetes.io/target-type', value: 'ip' },
            { key: 'alb.ingress.kubernetes.io/certificate-arn', value: 'arn:aws:acm:us-east-1:123456789:certificate/abc-123' },
          ],
        },
      },
      {
        id: 'service-1',
        type: 'k8sNode',
        position: { x: 250, y: 200 },
        data: {
          type: 'service',
          label: 'App Service',
          serviceName: 'app-service',
          port: 80,
          targetPort: 8080,
          serviceType: 'NodePort',
          selectorLabels: [{ key: 'app', value: 'myapp' }],
        },
      },
      {
        id: 'deployment-1',
        type: 'k8sNode',
        position: { x: 250, y: 350 },
        data: {
          type: 'deployment',
          label: 'App Deployment',
          deploymentName: 'app-deployment',
          replicas: 3,
          containerName: 'app',
          image: '123456789.dkr.ecr.us-east-1.amazonaws.com/myapp:latest',
          containerPort: 8080,
          envVars: [
            { key: 'AWS_REGION', value: 'us-east-1' },
            { key: 'APP_ENV', value: 'production' },
          ],
          labels: [{ key: 'app', value: 'myapp' }],
          volumeMounts: [{ name: 'data', mountPath: '/data' }],
        },
      },
      {
        id: 'hpa-1',
        type: 'k8sNode',
        position: { x: 500, y: 350 },
        data: {
          type: 'hpa',
          label: 'Auto Scaler',
          name: 'app-hpa',
          targetDeployment: 'app-deployment',
          minReplicas: 2,
          maxReplicas: 10,
          cpuTarget: 70,
          memoryTarget: 80,
        },
      },
      {
        id: 'secret-1',
        type: 'k8sNode',
        position: { x: 50, y: 500 },
        data: {
          type: 'secret',
          label: 'AWS Secrets',
          name: 'app-secrets',
          secretType: 'Opaque',
          data: [
            { key: 'DB_PASSWORD', value: 'stored-in-secrets-manager' },
            { key: 'API_KEY', value: 'stored-in-parameter-store' },
          ],
        },
      },
      {
        id: 'pvc-1',
        type: 'k8sNode',
        position: { x: 450, y: 500 },
        data: {
          type: 'pvc',
          label: 'EBS Volume',
          name: 'app-data',
          storageClassName: 'gp3',
          size: '50Gi',
          accessModes: ['ReadWriteOnce'],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'ingress-1', target: 'service-1' },
      { id: 'e2', source: 'service-1', target: 'deployment-1' },
      { id: 'e3', source: 'hpa-1', target: 'deployment-1' },
      { id: 'e4', source: 'deployment-1', target: 'secret-1' },
      { id: 'e5', source: 'deployment-1', target: 'pvc-1' },
    ],
  },
  {
    id: 'gcp-gke-app',
    name: 'GCP GKE Application',
    description: 'GKE with Cloud SQL Proxy, Artifact Registry, and GCE Persistent Disk',
    nodes: [
      {
        id: 'ingress-1',
        type: 'k8sNode',
        position: { x: 250, y: 50 },
        data: {
          type: 'ingress',
          label: 'GCP Ingress',
          host: 'app.example.com',
          paths: [{ path: '/', pathType: 'Prefix', serviceName: 'web-service', servicePort: 80 }],
          ingressClassName: 'gce',
          enableTLS: true,
          tlsSecretName: 'gcp-tls-cert',
          annotations: [
            { key: 'kubernetes.io/ingress.class', value: 'gce' },
            { key: 'kubernetes.io/ingress.global-static-ip-name', value: 'web-static-ip' },
            { key: 'networking.gke.io/managed-certificates', value: 'web-cert' },
          ],
        },
      },
      {
        id: 'service-1',
        type: 'k8sNode',
        position: { x: 250, y: 200 },
        data: {
          type: 'service',
          label: 'Web Service',
          serviceName: 'web-service',
          port: 80,
          targetPort: 8080,
          serviceType: 'NodePort',
          selectorLabels: [{ key: 'app', value: 'web' }],
        },
      },
      {
        id: 'deployment-1',
        type: 'k8sNode',
        position: { x: 250, y: 350 },
        data: {
          type: 'deployment',
          label: 'Web App',
          deploymentName: 'web-deployment',
          replicas: 3,
          containerName: 'web',
          image: 'us-docker.pkg.dev/my-project/my-repo/web-app:v1.0',
          containerPort: 8080,
          envVars: [
            { key: 'DB_HOST', value: '127.0.0.1' },
            { key: 'DB_PORT', value: '5432' },
          ],
          labels: [{ key: 'app', value: 'web' }],
          volumeMounts: [{ name: 'data', mountPath: '/app/data' }],
        },
      },
      {
        id: 'sidecar-1',
        type: 'k8sNode',
        position: { x: 500, y: 350 },
        data: {
          type: 'sidecar',
          label: 'Cloud SQL Proxy',
          containerName: 'cloudsql-proxy',
          image: 'gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.0',
          containerType: 'sidecar',
          purpose: 'proxy',
          containerPort: 5432,
          envVars: [],
          command: ['/cloud-sql-proxy'],
          args: ['--port=5432', 'my-project:us-central1:my-db-instance'],
          volumeMounts: [],
          cloudProvider: 'none',
        },
      },
      {
        id: 'secret-1',
        type: 'k8sNode',
        position: { x: 50, y: 500 },
        data: {
          type: 'secret',
          label: 'GCP Secrets',
          name: 'gcp-app-secrets',
          secretType: 'Opaque',
          data: [
            { key: 'DB_PASSWORD', value: 'from-secret-manager' },
            { key: 'API_KEY', value: 'from-secret-manager' },
          ],
        },
      },
      {
        id: 'pvc-1',
        type: 'k8sNode',
        position: { x: 450, y: 500 },
        data: {
          type: 'pvc',
          label: 'GCE Persistent Disk',
          name: 'web-data',
          storageClassName: 'standard-rwo',
          size: '100Gi',
          accessModes: ['ReadWriteOnce'],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'ingress-1', target: 'service-1' },
      { id: 'e2', source: 'service-1', target: 'deployment-1' },
      { id: 'e3', source: 'deployment-1', target: 'sidecar-1' },
      { id: 'e4', source: 'deployment-1', target: 'secret-1' },
      { id: 'e5', source: 'deployment-1', target: 'pvc-1' },
    ],
  },
  {
    id: 'azure-aks-app',
    name: 'Azure AKS Application',
    description: 'AKS with Application Gateway, ACR, Key Vault, and Azure Disk',
    nodes: [
      {
        id: 'ingress-1',
        type: 'k8sNode',
        position: { x: 250, y: 50 },
        data: {
          type: 'ingress',
          label: 'App Gateway Ingress',
          host: 'app.example.com',
          paths: [{ path: '/', pathType: 'Prefix', serviceName: 'api-service', servicePort: 80 }],
          ingressClassName: 'azure-application-gateway',
          enableTLS: true,
          tlsSecretName: 'azure-tls-cert',
          annotations: [
            { key: 'appgw.ingress.kubernetes.io/backend-path-prefix', value: '/' },
            { key: 'appgw.ingress.kubernetes.io/ssl-redirect', value: 'true' },
            { key: 'appgw.ingress.kubernetes.io/cookie-based-affinity', value: 'Enabled' },
          ],
        },
      },
      {
        id: 'service-1',
        type: 'k8sNode',
        position: { x: 250, y: 200 },
        data: {
          type: 'service',
          label: 'API Service',
          serviceName: 'api-service',
          port: 80,
          targetPort: 3000,
          serviceType: 'ClusterIP',
          selectorLabels: [{ key: 'app', value: 'api' }],
        },
      },
      {
        id: 'deployment-1',
        type: 'k8sNode',
        position: { x: 250, y: 350 },
        data: {
          type: 'deployment',
          label: 'API Deployment',
          deploymentName: 'api-deployment',
          replicas: 2,
          containerName: 'api',
          image: 'myregistry.azurecr.io/api-app:v2.0',
          containerPort: 3000,
          envVars: [
            { key: 'AZURE_TENANT_ID', value: 'from-keyvault' },
            { key: 'DATABASE_URL', value: 'from-keyvault' },
          ],
          labels: [
            { key: 'app', value: 'api' },
            { key: 'azure.workload.identity/use', value: 'true' },
          ],
          volumeMounts: [{ name: 'secrets-store', mountPath: '/mnt/secrets' }],
        },
      },
      {
        id: 'secret-1',
        type: 'k8sNode',
        position: { x: 50, y: 500 },
        data: {
          type: 'secret',
          label: 'Key Vault Secrets',
          name: 'keyvault-secrets',
          secretType: 'Opaque',
          data: [
            { key: 'DATABASE_PASSWORD', value: 'synced-from-keyvault' },
            { key: 'STORAGE_KEY', value: 'synced-from-keyvault' },
          ],
        },
      },
      {
        id: 'pvc-1',
        type: 'k8sNode',
        position: { x: 450, y: 500 },
        data: {
          type: 'pvc',
          label: 'Azure Disk',
          name: 'api-storage',
          storageClassName: 'managed-csi-premium',
          size: '64Gi',
          accessModes: ['ReadWriteOnce'],
        },
      },
      {
        id: 'hpa-1',
        type: 'k8sNode',
        position: { x: 500, y: 350 },
        data: {
          type: 'hpa',
          label: 'API Autoscaler',
          name: 'api-hpa',
          targetDeployment: 'api-deployment',
          minReplicas: 2,
          maxReplicas: 8,
          cpuTarget: 75,
          memoryTarget: 85,
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'ingress-1', target: 'service-1' },
      { id: 'e2', source: 'service-1', target: 'deployment-1' },
      { id: 'e3', source: 'hpa-1', target: 'deployment-1' },
      { id: 'e4', source: 'deployment-1', target: 'secret-1' },
      { id: 'e5', source: 'deployment-1', target: 'pvc-1' },
    ],
  },
  {
    id: 'multi-cloud-app',
    name: 'Multi-Cloud Architecture',
    description: 'Hybrid cloud setup with external secrets, observability, and distributed storage',
    nodes: [
      {
        id: 'ingress-1',
        type: 'k8sNode',
        position: { x: 300, y: 30 },
        data: {
          type: 'ingress',
          label: 'Global Ingress',
          host: 'global.example.com',
          paths: [
            { path: '/api', pathType: 'Prefix', serviceName: 'api-service', servicePort: 80 },
            { path: '/admin', pathType: 'Prefix', serviceName: 'admin-service', servicePort: 80 },
          ],
          ingressClassName: 'nginx',
          enableTLS: true,
          tlsSecretName: 'wildcard-tls',
          annotations: [
            { key: 'cert-manager.io/cluster-issuer', value: 'letsencrypt-prod' },
            { key: 'nginx.ingress.kubernetes.io/rate-limit', value: '100' },
          ],
        },
      },
      {
        id: 'service-api',
        type: 'k8sNode',
        position: { x: 150, y: 180 },
        data: {
          type: 'service',
          label: 'API Service',
          serviceName: 'api-service',
          port: 80,
          targetPort: 8080,
          serviceType: 'ClusterIP',
          selectorLabels: [{ key: 'app', value: 'api' }],
        },
      },
      {
        id: 'service-admin',
        type: 'k8sNode',
        position: { x: 450, y: 180 },
        data: {
          type: 'service',
          label: 'Admin Service',
          serviceName: 'admin-service',
          port: 80,
          targetPort: 3000,
          serviceType: 'ClusterIP',
          selectorLabels: [{ key: 'app', value: 'admin' }],
        },
      },
      {
        id: 'deployment-api',
        type: 'k8sNode',
        position: { x: 150, y: 330 },
        data: {
          type: 'deployment',
          label: 'API App',
          deploymentName: 'api-deployment',
          replicas: 3,
          containerName: 'api',
          image: 'registry.example.com/api:v1.5',
          containerPort: 8080,
          envVars: [
            { key: 'CLOUD_PROVIDER', value: 'multi' },
            { key: 'TELEMETRY_ENDPOINT', value: 'otel-collector:4317' },
          ],
          labels: [{ key: 'app', value: 'api' }],
          volumeMounts: [{ name: 'cache', mountPath: '/cache' }],
        },
      },
      {
        id: 'deployment-admin',
        type: 'k8sNode',
        position: { x: 450, y: 330 },
        data: {
          type: 'deployment',
          label: 'Admin Panel',
          deploymentName: 'admin-deployment',
          replicas: 2,
          containerName: 'admin',
          image: 'registry.example.com/admin:v2.0',
          containerPort: 3000,
          envVars: [
            { key: 'NODE_ENV', value: 'production' },
          ],
          labels: [{ key: 'app', value: 'admin' }],
          volumeMounts: [],
        },
      },
      {
        id: 'sidecar-observability',
        type: 'k8sNode',
        position: { x: 600, y: 330 },
        data: {
          type: 'sidecar',
          label: 'OTEL Collector',
          containerName: 'otel-collector',
          image: 'otel/opentelemetry-collector:0.91.0',
          containerType: 'sidecar',
          purpose: 'monitoring',
          containerPort: 4317,
          envVars: [],
          command: ['/otelcol'],
          args: ['--config=/etc/otel/config.yaml'],
          volumeMounts: [],
          cloudProvider: 'none',
        },
      },
      {
        id: 'configmap-1',
        type: 'k8sNode',
        position: { x: 30, y: 500 },
        data: {
          type: 'configmap',
          label: 'App Config',
          name: 'app-config',
          data: [
            { key: 'FEATURE_FLAGS', value: 'feature1,feature2,feature3' },
            { key: 'LOG_LEVEL', value: 'info' },
            { key: 'CACHE_TTL', value: '3600' },
          ],
        },
      },
      {
        id: 'secret-1',
        type: 'k8sNode',
        position: { x: 200, y: 500 },
        data: {
          type: 'secret',
          label: 'External Secrets',
          name: 'external-secrets',
          secretType: 'Opaque',
          data: [
            { key: 'AWS_SECRET', value: 'from-aws-secrets-manager' },
            { key: 'GCP_SECRET', value: 'from-gcp-secret-manager' },
            { key: 'AZURE_SECRET', value: 'from-azure-keyvault' },
          ],
        },
      },
      {
        id: 'pvc-1',
        type: 'k8sNode',
        position: { x: 370, y: 500 },
        data: {
          type: 'pvc',
          label: 'Shared Storage',
          name: 'shared-data',
          storageClassName: 'standard',
          size: '100Gi',
          accessModes: ['ReadWriteMany'],
        },
      },
      {
        id: 'cronjob-1',
        type: 'k8sNode',
        position: { x: 540, y: 500 },
        data: {
          type: 'cronjob',
          label: 'Backup Job',
          name: 'backup-cronjob',
          schedule: '0 3 * * *',
          image: 'backup-utility:latest',
          command: ['/bin/sh'],
          args: ['-c', 'backup-script.sh'],
        },
      },
    ],
    edges: [
      { id: 'e1', source: 'ingress-1', target: 'service-api' },
      { id: 'e2', source: 'ingress-1', target: 'service-admin' },
      { id: 'e3', source: 'service-api', target: 'deployment-api' },
      { id: 'e4', source: 'service-admin', target: 'deployment-admin' },
      { id: 'e5', source: 'deployment-api', target: 'sidecar-observability' },
      { id: 'e6', source: 'deployment-api', target: 'configmap-1' },
      { id: 'e7', source: 'deployment-api', target: 'secret-1' },
      { id: 'e8', source: 'deployment-api', target: 'pvc-1' },
      { id: 'e9', source: 'deployment-admin', target: 'secret-1' },
      { id: 'e10', source: 'cronjob-1', target: 'pvc-1' },
    ],
  },
];
